### ISSUE TITLE
PHP 8?

### ISSUE THREAD

**Issue by Punktraum** [terminal42/contao-password-validation#12]
Da Ticket #9 geschlossen wurde und mein nachträglicher Kommentar (vermutlich) deshalb nicht mehr berücksichtigt wurde, erlaube ich mir hierfür ein neues Ticket zu eröffnen.

Contao 4.11.19
Contao Manager 1.4.10
PHP Version 8.0.13

Inzwischen kann ich die Erweiterung zwar installieren, der Aufruf des Install-Tools fält dann aber auf die Nase (HTTP ERROR 500) und die anschliessende Systemprüfung oder auch die versuchte Systemwiederherstellung gibt folgenden Fehler aus (Konsolenausgabe):

```
vendor/bin/contao-console contao:version
$ /opt/plesk/php/8.0/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Zurich /home/httpd/vhosts/ha/tld/vendor/contao/manager-bundle/bin/contao-console cache:clear --env=prod --no-warmup
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /home/httpd/vhosts/ha/tld/vendor/terminal42/contao-password-validation/src/DependencyInjection/Configuration.php on line 23 and at least 1 expected in /home/httpd/vhosts/ha/tld/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
Stack trace:
#0 /home/httpd/vhosts/ha/tld/vendor/terminal42/contao-password-validation/src/DependencyInjection/Configuration.php(23): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
#1 /home/httpd/vhosts/ha/tld/vendor/symfony/config/Definition/Processor.php(50): Terminal42\PasswordValidationBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
#2 /home/httpd/vhosts/ha/tld/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(Terminal42\PasswordValidationBundle\DependencyInjection\Configuration), Array)
#3 /home/httpd/vhosts/ha/tld/vendor/terminal42/contao-password-validation/src/DependencyInjection/Terminal42PasswordValidationExtension.php(34): Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration(Object(Terminal42\PasswordValidationBundle\DependencyInjection\Configuration), Array)
#4 /home/httpd/vhosts/ha/tld/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): Terminal42\PasswordValidationBundle\DependencyInjection\Terminal42PasswordValidationExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#5 /home/httpd/vhosts/ha/tld/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Contao\ManagerPlugin\Config\ContainerBuilder))
#6 /home/httpd/vhosts/ha/tld/vendor/symfony/dependency-injection/Compiler/Compiler.php(91): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Contao\ManagerPlugin\Config\ContainerBuilder))
#7 /home/httpd/vhosts/ha/tld/vendor/symfony/dependency-injection/ContainerBuilder.php(731): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Contao\ManagerPlugin\Config\ContainerBuilder))
#8 /home/httpd/vhosts/ha/tld/vendor/symfony/http-kernel/Kernel.php(541): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#9 /home/httpd/vhosts/ha/tld/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(321): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#10 /home/httpd/vhosts/ha/tld/vendor/symfony/http-kernel/Kernel.php(780): Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer()
#11 /home/httpd/vhosts/ha/tld/vendor/symfony/http-kernel/Kernel.php(121): Symfony\Component\HttpKernel\Kernel->preBoot()
#12 /home/httpd/vhosts/ha/tld/vendor/symfony/framework-bundle/Console/Application.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#13 /home/httpd/vhosts/ha/tld/vendor/symfony/framework-bundle/Console/Application.php(74): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#14 /home/httpd/vhosts/ha/tld/vendor/symfony/console/Application.php(166): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/httpd/vhosts/ha/tld/vendor/contao/manager-bundle/bin/contao-console(37): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#16 {main}
  thrown in /home/httpd/vhosts/ha/tld/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
# Process terminated with exit code 255
# Result: Unknown error
```

**Backend und Installtool sind erst nach einer Deinstallation der Erweiterung im abgesicherten Modus wieder erreichbar.**
Identisches Verhalten übrigens auch nach Update von Contao auf V4.12.3.

**Comment by richardhj** [comment]
Alright, ist gefixt in d83fbb54511bf0dca09678fe968f18d4055bb911.
